services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-server
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL-jdbc:postgresql://db-postgres:5432/job_swipe}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME-qh47Qsmu19JJRuMq}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD-TwwlZL9j10wyziG3}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST-db-redis}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT-6379}
      - SPRING_REDIS_USERNAME=${SPRING_REDIS_USERNAME}
      - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
      - SPRING_REDIS_SSL_ENABLED=${SPRING_REDIS_SSL_ENABLED-false}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST-smtp.gmail.com}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT-587}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_ACCESS_TOKEN_SECRET_KEY=${JWT_ACCESS_TOKEN_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_MS=${JWT_ACCESS_TOKEN_EXPIRATION_MS}
      - JWT_REFRESH_TOKEN_SECRET_KEY=${JWT_REFRESH_TOKEN_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRATION_MS=${JWT_REFRESH_TOKEN_EXPIRATION_MS}
      - RESET_PASSWORD_CODE_EXPIRATION_MS=${RESET_PASSWORD_CODE_EXPIRATION_MS}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MAX_SENT_INTERVIEW_INVITATION_MAIL_PER_DAY_AND_USER=${MAX_SENT_INTERVIEW_INVITATION_MAIL_PER_DAY_AND_USER}
    env_file:
      - .env
    networks:
      - job-swipe-network
  postgres:
    image: postgres:15
    container_name: db-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB-job_swipe}
      - POSTGRES_USER=${POSTGRES_USER-qh47Qsmu19JJRuMq}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-TwwlZL9j10wyziG3}
    env_file:
      - .env
    ports:
      - "6002:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
    networks:
      - job-swipe-network
  redis:
    image: redis:6.2-alpine
    container_name: db-redis
    restart: always
    ports:
      - "6003:6379"
    volumes:
      - redis:/data
    networks:
      - job-swipe-network

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  job-swipe-network:
    name: job-swipe-network
    driver: bridge
