services:
  application:
    image: docker-spring-boot-postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-server
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/job_swipe
      - SPRING_DATASOURCE_USERNAME=qh47Qsmu19JJRuMq
      - SPRING_DATASOURCE_PASSWORD=TwwlZL9j10wyziG3
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_USERNAME=null
      - SPRING_REDIS_PASSWORD=null
      - SPRING_REDIS_SSL_ENABLED=false
      - JWT_ACCESS_TOKEN_SECRET_KEY=6hSmRTTEvThV9PGxjCTKRJI3OPsrP45iU9eZOkCmUZE=
      - JWT_ACCESS_TOKEN_EXPIRATION_MS=7200000
      - JWT_REFRESH_TOKEN_SECRET_KEY=lEhcgErgeknNv9/cp1Sh5RXTaB4RTVCCdAnPPewpSMM=
      - JWT_REFRESH_TOKEN_EXPIRATION_MS=2592000000
      - RESET_PASSWORD_CODE_EXPIRATION_MS=3600000
      - S3_BUCKET_NAME=pbl5-bucket
      - MAIL_TRAP_URL=https://send.api.mailtrap.io/api/send
      - MAIL_TRAP_API_KEY=b0af10cf775e3af21e7c8200312db25f
      - MAIL_TRAP_FROM_EMAIL=mailtrap@demomailtrap.com
      - MAIL_TRAP_FROM_EMAIL_NAME=Job Swipe
      - MAIL_TRAP_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID=58cc4e51-3dcd-44d9-b0f3-8d87551fc735
    networks:
      - job-swipe-network
  postgres:
    image: postgres:15
    container_name: db-postgres
    restart: always
    environment:
      - POSTGRES_DB=job_swipe
      - POSTGRES_USER=qh47Qsmu19JJRuMq
      - POSTGRES_PASSWORD=TwwlZL9j10wyziG3
    ports:
      - "6002:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
    networks:
      - job-swipe-network
  redis:
    image: redis:latest
    container_name: db-redis
    ports:
      - "6003:6379"
    volumes:
      - redis:/data
    networks:
      - job-swipe-network

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  job-swipe-network:
    driver: bridge
