# git commit -m "PBL-850 set up base"
# git commit -m "PBL-850 set up enviroment on render"
# git commit -m "PBL-846 set up db"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=job_swipe
      - POSTGRES_USER=qh47Qsmu19JJRuMq
      - POSTGRES_PASSWORD=TwwlZL9j10wyziG3
    ports:
      - "6002:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6003:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local
