server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/pbl5
    username: postgres
    password: 123456Aa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # UPDATE
      # The database must be created beforehand.
      # The update option will refresh the database
      #   if there are changes to the tables within that database
      #   (only applied to existing fields).
      #
      # CREATE
      # The previous database will be deleted, creating a new database
      #   (Data in the old database will also be deleted).
      # This option is used when:
      #   1. Creating a new database
      #   2. Adding (or deleting) a field in a table of that database.
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



