server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:6002/job_swipe
    username: qh47Qsmu19JJRuMq
    password: TwwlZL9j10wyziG3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 6000
  data:
    redis:
      host: localhost
      port: 6003

logging:
  level:
    org.springframework.security: trace
  file:
    name: log/dev.log

application:
  jwt:
    access-token-secret-key: YAOmGqqMFI2T2SJqIw7WV1h+V5miq9zS7uF8f/kBBqx55YqAwWhJTCLxLaxwKsRg
    access-token-expiration-ms: 7200000
    refresh-token-secret-key: DHVmGqqMFI2T2SJdIw7dV1h+V5miq9zSvuF6f/kBB1x55Y3AwWdTCLxLaxwKsRg
    refresh-token-expiration-ms: 2592000000
  s3:
    bucket-name: pbl5-bucket
  server.socket:
    port: 8888
  mail-trap:
    url: https://send.api.mailtrap.io/api/send
    api-key: b0af10cf775e3af21e7c8200312db25f
    from-email: mailtrap@demomailtrap.com
    from-email-name: Job Swipe
    forgot-password-email-template-id: 58cc4e51-3dcd-44d9-b0f3-8d87551fc735
