server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    time-zone: UTC
    deserialization:
      adjust-dates-to-context-time-zone: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://dpg-cohl1otjm4es739anpl0-a.singapore-postgres.render.com:5432/job_swipe_rado
    username: job_swipe_rado_user
    password: 43RcjIyvinBmuDK2BGY6v7YzsFmBwHmw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database: postgresql
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 6000
  data:
    redis:
      host: singapore-redis.render.com
      port: 6379
      username: red-cohl2tljm4es739ao8og
      password: nUWDQGllxG5RqgN4ddRl9cmRo8gJeJtE
      ssl:
        enabled: true
      jedis:
        pool:
          enabled: true
          max-active: 16
          max-idle: 16
          min-idle: 8
          max-wait: 1800 # 30 minutes

logging:
  level:
    org.springframework.security: trace
  file:
    name: log/dev.log

application:
  jwt:
    access-token-secret-key: YAOmGqqMFI2T2SJqIw7WV1h+V5miq9zS7uF8f/kBBqx55YqAwWhJTCLxLaxwKsRg
    access-token-expiration-ms: 7200000
    refresh-token-secret-key: DHVmGqqMFI2T2SJdIw7dV1h+V5miq9zSvuF6f/kBB1x55Y3AwWdTCLxLaxwKsRg
    refresh-token-expiration-ms: 2592000000
  reset-password-code-expiration-ms: 3600000
  s3:
    bucket-name: pbl5-bucket
  server.socket:
    port: 8888
  mail-trap:
    url: https://send.api.mailtrap.io/api/send
    api-key: b0af10cf775e3af21e7c8200312db25f
    from-email: mailtrap@demomailtrap.com
    from-email-name: Job Swipe
    forgot-password-email-template-id: 58cc4e51-3dcd-44d9-b0f3-8d87551fc735
